# Generated by Django 3.1.2 on 2020-11-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='rg_orgao_emissor',
            new_name='rg_orgao_emissor_2',
        ),
    ]
