# Generated by Django 3.1.2 on 2020-10-21 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_auto_20201021_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
