# Generated by Django 3.1.2 on 2020-11-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_auto_20201103_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='rg_orgao_emissor_2',
            new_name='rg_orgao_emissor',
        ),
    ]
